### ISSUE TITLE
Clock frequency 170 too low, resetting to 180

### ISSUE THREAD

**Issue by dennisblokland** [wareck/cgminer-lketc#1]
ive set my clock frequency to 220 but on startup it gives this message
"Clock frequency 170 too low, resetting to 180"
is this right?

**Comment by wareck** [comment]
yes is just for testing and find usb miner otherwise sometime it doesn't 
see it


Olivier

**Comment by wareck** [comment]
I've just fixed it :)

**Comment by dennisblokland** [comment]
nice ty
