### ISSUE TITLE
Gawminer FURY not accepting shares

### ISSUE THREAD

**Issue by jojoosinga** [wareck/cgminer-lketc#1]
Ey,

I am trying to run the miner on my GAWminer Fury but it is just not working.

This is my start command `sudo ./cgminer --scrypt --zeus-chips 6 --zeus-clock 328 -o stratum+tcp://stratum.aikapool.com:7915 -u jojoosinga.gawfury -p x`

It detects it as blizzard and seems to start mining but not accepting shares

https://ibb.co/ZRDybky

**Comment by csa402** [comment]
give me some minutes I'll do the test

**Comment by wareck** [comment]
hello
I think (but maybe i'm wrong) there is too much people on this pool and you may need more power (more miner or high GH/S miner)
I try with my gawminer and I have the same results...

![image](https://user-images.githubusercontent.com/5462099/200960872-686d1128-54d6-4ebc-a056-534d3001e67d.png)

By the way, just for testing , try this command line :
sudo ./cgminer --scrypt -o stratum+tcp://eu-de02.miningrigrentals.com:3333 -u wareck.262669 -p x

You will have accepted shares very quickly ...
If YES, you have quickly shares on this pool => it's link to your pool and not linked to software/hardware
I've got this in 10 minutes : 

![image](https://user-images.githubusercontent.com/5462099/200962447-cfeedca9-e247-49c4-ba8e-c6220c660720.png)

**Comment by wareck** [comment]
that's it
on the pool the difficulty is too high.
in other words, the round is over before your miner starts calculating.

Mining is like a competition, on a pool, it is a collective work, you win in proportion to what you mined.
The others have faster and more powerful calculators.
Yours will only get the crumbs, but for the moment it can't even get a place in the race.

I have just restarted mine to see, and as you can see the difficulty keeps increasing.
This means that it's getting harder and harder to get a place and that the gain in % of your material is going down.

![image](https://user-images.githubusercontent.com/5462099/200964303-b38f451c-c1a6-4730-8331-696fbe87a28e.png)

the other thing you can look at is the WU to the right of the miner's line.

This is an efficiency indicator, basically "useful work".
It is at 0 on this pool, it indicates that the miner is not doing anything and is waiting to get work...

If you look at my example the WU goes to 1092/m it means that it will do a certain number of jobs and that the machine is efficient.

The smaller the WU, the less you earn...
It can happen to have a very high WU but no sharing, in this case we know that sooner or later the sharing will take place
But with a WU at 0 it's dead

try another pool or another scrypt currency.

**Comment by jojoosinga** [comment]
Thank you so much!
